name: Test Workflow

on:
  # Triggers the workflow when called from organization repository
  workflow_call:
    inputs:
      test_param:
        required: false
        default: 'value'
        type: string

jobs:
#  release:
#    # The type of runner that the job will run on
#    runs-on: ubuntu-20.04
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#
#      - name: Fetch all tags
#        run: |
#          git config --global user.email "actions@github.com"
#          git config --global user.name "Github actions"
#          git fetch --tags --unshallow --prune
#
#      - name: Publish release
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: |
#          latest_tag=v${{github.run_number}}
#          gh release create $latest_tag --generate-notes

  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    steps:
      # Checkout Project
#      - name: Checkout
#        uses: actions/checkout@v2
#        with:
#          ref: ${{ github.ref }}

      - name: Project
        run: |
          cat etc/docs/example.txt
          ls
          cd ..
          ls